Zextras/carbonio-files-ui-common

views/FileView.tsx, views/FilterView.tsx, views/FolderView.tsx, views/SearchView.tsx, views/UploadView.tsx, views/components/previewer/PreviewerBase.tsx
=> fix: remove shell references from common submodule

constants/index.ts, hooks/useCreateDocsFile.ts, mocks/handleCreateDocsFileRequest.ts, utils/utils.ts, views/components/FolderList.test.tsx
=> refactor: update docs endpoints

views/components/preview/PdfPreview.tsx
=> fix: update pdf preview z-index value

views/FileView.tsx, views/FilterView.test.tsx, views/FilterView.tsx, views/FolderView.test.tsx, views/FolderView.tsx, views/SearchView.test.tsx, views/SearchView.tsx, views/UploadView.tsx
=> fix: remove useless new actions on views unmount

utils/utils.ts, views/components/NodeAvatarIcon.tsx, views/components/NodeListItem.tsx
=> feat: add thumbnails on list avatars

hooks/graphql/useUpdateFolderContent.test.ts, hooks/graphql/useUpdateFolderContent.ts
=> fix: fix upload folder content in update unordered items case

constants/index.ts, mocks/handleGetPreviewRequest.ts, utils/utils.ts, views/components/NodeListItem.test.tsx, views/components/NodeListItem.tsx
=> feat: support preview of documents

types/common.ts, views/components/NodesSelectionModalContent.tsx
=> feat: get link function integration

utils/ActionsFactory.ts, views/components/List.tsx, views/components/NodeListItem.tsx, views/components/NodeListItemWrapper.tsx, views/components/PreviewPanelActions.tsx
=> feat: allow send via mail

mocks/mockUtils.ts
=> refactor: replace faker deprecated usage

constants/index.ts, utils/testUtils.tsx, views/components/DisplayerPreview.tsx, views/components/List.preview.test.tsx, views/components/List.tsx, views/components/NodeListItem.tsx, views/components/PreviewPanelActions.tsx
=> fix: show preview for pdf with size 0

apollo/uploadVar.ts, constants/index.ts, hooks/useUpload.ts, mocks/handleUploadFileRequest.ts, types/common.ts, views/components/UploadList.test.tsx, views/components/UploadList.tsx, views/components/UploadListItem.tsx, views/components/UploadListItemWrapper.test.tsx
=> feat: add limit to upload queue

hooks/graphql/mutations/useUpdateLinkMutation.ts, hooks/useErrorHandler.ts
=> feat: add update link function

constants/index.ts, design_system_fork/SharesChipInput.jsx, types/common.ts, types/network.ts, utils/utils.ts, views/components/sharing/AddShareChip.test.tsx, views/components/sharing/AddShareChip.tsx, views/components/sharing/AddSharing.test.tsx, views/components/sharing/AddSharing.tsx, views/components/sharing/ChipWithPopover.tsx, views/components/sharing/EditShareChip.test.tsx, views/components/sharing/EditShareChip.tsx, views/components/sharing/NodeSharing.test.tsx, views/components/sharing/NodeSharing.tsx, views/components/sharing/ShareChipLabel.tsx
=> Files 313 improve chip of shares

hooks/graphql/mutations/useMoveNodesMutation.ts, hooks/graphql/queries/useGetChildQuery.ts, utils/mockUtils.ts, views/FolderView.copy.test.tsx, views/FolderView.createDocsFile.test.tsx, views/FolderView.createFolder.test.tsx, views/FolderView.dragAndDrop.test.tsx, views/FolderView.flag.test.tsx, views/FolderView.getChildren.test.tsx, views/FolderView.markForDeletion.test.tsx, views/FolderView.move.test.tsx, views/FolderView.rename.test.tsx, views/FolderView.selectionMode.test.tsx, views/FolderView.sorting.test.tsx, views/FolderView.test.tsx, views/components/FilterList.dragAndDrop.test.tsx, views/components/FilterList.markForDeletion.test.tsx, views/components/FilterList.test.tsx, views/components/List.tsx, views/components/SearchList.test.tsx
=> feat: allow drop on opened folder during drag-move

constants/index.ts, utils/utils.ts, views/FileView.tsx, views/FilterView.tsx, views/FolderView.tsx, views/SearchView.tsx, views/UploadView.tsx
=> feat: update new document action labels

views/components/DisplayerActions.tsx, views/components/DisplayerPreview.tsx, views/components/List.tsx, views/components/NodeDetails.tsx, views/components/NodeListItem.tsx
=> feat: integrate preview document selector

hooks/useDroppableCrumbs.ts, utils/testUtils.tsx, views/FolderView.dragAndDrop.test.tsx, views/components/Displayer.unsavedChanges.addLink.test.tsx, views/components/Displayer.unsavedChanges.addShare.test.tsx, views/components/Displayer.unsavedChanges.editDescription.test.tsx, views/components/Displayer.unsavedChanges.editLink.test.tsx, views/components/Displayer.unsavedChanges.editShare.test.tsx, views/components/HeaderBreadcrumbs.test.tsx, views/components/List.tsx, views/components/NodeListItem.test.tsx
=> test: fix broken tests

views/components/DisplayerNode.tsx, views/components/List.preview.test.tsx, views/components/NodeListItem.test.tsx
=> fix: apply TabBar breaking change

views/components/sharing/AddSharing.test.tsx, views/components/sharing/AddSharing.tsx, views/components/sharing/NodeSharing.test.tsx
=> fix: hide custom message input

hooks/modals/useCreateModal.tsx, hooks/modals/useRenameModal.tsx, views/components/CopyNodesModalContent.tsx, views/components/MoveNodesModalContent.tsx, views/components/RouteLeavingGuard.tsx, views/components/UpdateNodeNameModalContent.tsx
Revert UI differences introduced with FILES-438
refs: FILES-483
=> fix: update modals to restore spaces and fonts

views/components/List.tsx
=> feat: disable force-cache to allow revalidation

apollo/cacheUtils.ts, apollo/index.ts, hooks/graphql/useUpdateFolderContent.ts
refs: FILES-185 FILES-501 FILES-396
=> refactor: move cache utils out of hook

utils/utils.ts
=> feat: add destinationId in upload-to

utils/utils.test.ts, utils/utils.ts, views/components/Dropzone.tsx, views/components/DropzoneModal.tsx, views/components/EmptyDisplayer.tsx, views/components/ModalList.tsx, views/components/ModalRootsList.tsx, views/components/NodeListItem.tsx, views/components/ScrollContainer.tsx, views/components/StyledComponents.tsx, views/components/sharing/NodeSharing.tsx, views/components/versioning/Versioning.tsx
=> refactor: replace calc with cssCalcBuilder util

utils/utils.test.ts, utils/utils.ts, views/components/Dropzone.tsx, views/components/DropzoneModal.tsx, views/components/EmptyDisplayer.tsx, views/components/ModalList.tsx, views/components/ModalRootsList.tsx, views/components/NodeListItem.tsx, views/components/ScrollContainer.tsx, views/components/StyledComponents.tsx, views/components/sharing/NodeSharing.tsx, views/components/versioning/Versioning.tsx
=> fix: fix typo in calc which is causing the broken ui in dev package

utils/utils.ts, views/components/NodeDetails.test.tsx, views/components/NodeDetails.tsx
=> fix: disable thumbnail for docs documents

utils/ActionsFactory.ts, views/FolderView.createDocsFile.test.tsx, views/FolderView.createFolder.test.tsx, views/FolderView.tsx, views/components/ContextualMenu.tsx, views/components/DisplayerActions.tsx, views/components/EmptySpaceFiller.tsx, views/components/List.tsx, views/components/ListContent.tsx, views/components/ListHeader.tsx, views/components/NodeHoverBar.test.tsx, views/components/NodeHoverBar.tsx, views/components/NodeListItem.tsx, views/components/NodeListItemWrapper.tsx, views/components/ScrollContainer.tsx, views/components/UploadList.tsx, views/components/UploadListItem.tsx
=> refactor: use CollapsingActions component where possible
